all:
	cd my/; make
	cd dl/; make
	cd src/; make

clean:
	cd my/; make clean
	cd dl/; make clean
	cd src/; make clean

fclean:
	cd my/; make fclean
	cd dl/; make fclean
	cd src/; make fclean

re:
	cd my/; make re
	cd dl/; make re
	cd src/; make re
